[2024-09-15 16:58:32,242] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_clima.cargar_data manual__2024-09-15T16:58:27.671834+00:00 [queued]>
[2024-09-15 16:58:32,259] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_clima.cargar_data manual__2024-09-15T16:58:27.671834+00:00 [queued]>
[2024-09-15 16:58:32,260] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 16:58:32,261] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-15 16:58:32,263] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 16:58:32,283] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2024-09-15 16:58:27.671834+00:00
[2024-09-15 16:58:32,289] {standard_task_runner.py:52} INFO - Started process 1135 to run task
[2024-09-15 16:58:32,292] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_clima', 'cargar_data', 'manual__2024-09-15T16:58:27.671834+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_clima.py', '--cfg-path', '/tmp/tmpw0hk34cs', '--error-file', '/tmp/tmpqycnw2em']
[2024-09-15 16:58:32,295] {standard_task_runner.py:80} INFO - Job 27: Subtask cargar_data
[2024-09-15 16:58:32,379] {task_command.py:371} INFO - Running <TaskInstance: dag_clima.cargar_data manual__2024-09-15T16:58:27.671834+00:00 [running]> on host 4abe27884306
[2024-09-15 16:58:32,473] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=EmanuelGomez
AIRFLOW_CTX_DAG_ID=dag_clima
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-15T16:58:27.671834+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-15T16:58:27.671834+00:00
[2024-09-15 16:58:33,846] {logging_mixin.py:115} INFO - Conexi√≥n exitosa a Redshift
[2024-09-15 16:58:33,868] {logging_mixin.py:115} INFO - {"time":{"0":"2024-09-15","1":"2024-09-16","2":"2024-09-17","3":"2024-09-18","4":"2024-09-19","5":"2024-09-20","6":"2024-09-21"},"temperature_max":{"0":17.38,"1":21.43,"2":21.58,"3":22.32,"4":21.59,"5":20.25,"6":21.1},"temperature_min":{"0":11.2,"1":11.73,"2":15.56,"3":15.83,"4":16.39,"5":13.61,"6":14.66},"precipitation":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":18.3,"5":0.0,"6":0.0},"sede1":{"0":"Devoto","1":"Devoto","2":"Devoto","3":"Devoto","4":"Almagro","5":"Devoto","6":"Devoto"},"sede2":{"0":"Floresta","1":"Floresta","2":"Floresta","3":"Floresta","4":"Caballito","5":"Floresta","6":"Floresta"}}
[2024-09-15 16:58:33,869] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/cargar_data.py", line 33, in cargar_data
    df = pd.DataFrame.to_json(xcom_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2571, in to_json
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 111, in to_json
    raise NotImplementedError("'obj' should be a Series or a DataFrame")
NotImplementedError: 'obj' should be a Series or a DataFrame
[2024-09-15 16:58:33,903] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_clima, task_id=cargar_data, execution_date=20240915T165827, start_date=20240915T165832, end_date=20240915T165833
[2024-09-15 16:58:33,929] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task cargar_data ('obj' should be a Series or a DataFrame; 1135)
[2024-09-15 16:58:33,954] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 16:58:34,001] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
